### ISSUE TITLE
Update sign up link

### ISSUE THREAD

**Issue by dannyflatiron** [Nexmo/nexmo-rack#11]
File nexmo_rack.gemspec [line 13](https://github.com/Nexmo/nexmo-rack/blob/79cd4c33d57ac983cdd30b35b9b45aca932d199e/nexmo_rack.gemspec#L13) does not direct user to sign up page. Is this open to change with this link, https://dashboard.nexmo.com/sign-up? If so I can do this.

**Comment by bencgreenberg** [comment]
Sure, that would be a helpful contribution. Feel free to raise it, @dannyflatiron!
